#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""
dictee-setup — Voice dictation configuration
Qt6 UI to configure keyboard shortcut and translation options.
Saves to ~/.config/dictee.conf (shell format, sourceable by dictee).
Supports PyQt6 (preferred) and PySide6 (fallback).
"""

import gettext
import os
import re
import shutil
import subprocess
import locale
import tempfile

try:
    from PyQt6.QtCore import Qt, QThread, pyqtSignal as Signal
    from PyQt6.QtGui import QKeySequence, QIcon
    from PyQt6.QtWidgets import (
        QApplication, QDialog, QVBoxLayout, QHBoxLayout, QGroupBox,
        QLabel, QPushButton, QRadioButton, QButtonGroup, QComboBox,
        QFormLayout, QProgressBar, QMessageBox, QSizePolicy, QCheckBox,
        QFrame, QScrollArea, QWidget,
    )
except ImportError:
    from PySide6.QtCore import Qt, QThread, Signal
    from PySide6.QtGui import QKeySequence, QIcon
    from PySide6.QtWidgets import (
        QApplication, QDialog, QVBoxLayout, QHBoxLayout, QGroupBox,
        QLabel, QPushButton, QRadioButton, QButtonGroup, QComboBox,
        QFormLayout, QProgressBar, QMessageBox, QSizePolicy, QCheckBox,
        QFrame, QScrollArea, QWidget,
    )

# === i18n ===

LOCALE_DIRS = [
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "share", "locale"),
    os.path.expanduser("~/.local/share/locale"),
    "/usr/local/share/locale",
    "/usr/share/locale",
]

for _d in LOCALE_DIRS:
    if os.path.isdir(_d):
        gettext.bindtextdomain("dictee", _d)
        break

gettext.textdomain("dictee")
_ = gettext.gettext

_NATIVE_TEXT = QKeySequence.SequenceFormat.NativeText

# === Configuration ===

CONF_PATH = os.path.join(
    os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config")),
    "dictee.conf",
)

LANGUAGES = [
    ("fr", "Français"),
    ("en", "English"),
    ("es", "Español"),
    ("de", "Deutsch"),
    ("it", "Italiano"),
    ("pt", "Português"),
    ("nl", "Nederlands"),
    ("pl", "Polski"),
    ("ru", "Русский"),
    ("zh", "中文"),
    ("ja", "日本語"),
    ("ko", "한국어"),
    ("ar", "العربية"),
]

DICTEE_COMMAND = "/usr/bin/dictee"
DICTEE_TRANSLATE_COMMAND = "/usr/bin/dictee --translate"
DICTEE_DESKTOP = "dictee.desktop"
DICTEE_TRANSLATE_DESKTOP = "dictee-translate.desktop"
ANIMATION_SPEECH_REPO = "rcspam/animation-speech"
ANIMATION_SPEECH_BIN = "animation-speech-ctl"

# === Détection DE ===


def detect_desktop():
    """Retourne (nom_affiché, type) avec type = 'kde' | 'gnome' | 'unsupported'."""
    desktop = os.environ.get("XDG_CURRENT_DESKTOP", "").upper()
    if "KDE" in desktop:
        return "KDE Plasma", "kde"
    for name in ("GNOME", "UNITY", "CINNAMON"):
        if name in desktop:
            label = desktop.replace(";", " / ").title()
            return label, "gnome"
    raw = os.environ.get("XDG_CURRENT_DESKTOP", _("unknown"))
    return raw, "unsupported"


# === Config fichier ===


def load_config():
    """Charge dictee.conf et retourne un dict des valeurs."""
    conf = {}
    if os.path.isfile(CONF_PATH):
        with open(CONF_PATH) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                m = re.match(r"^([A-Z_]+)=(.*)$", line)
                if m:
                    conf[m.group(1)] = m.group(2)
    return conf


def save_config(backend, lang_source, lang_target, clipboard=True, animation="speech",
                ollama_model="translategemma", ollama_cpu=False, trans_engine="google",
                lt_port=5000, asr_backend="parakeet", whisper_model="small",
                whisper_lang="", vosk_model="fr"):
    """Écrit dictee.conf (sans DICTEE_TRANSLATE — le déclenchement est au runtime)."""
    os.makedirs(os.path.dirname(CONF_PATH), exist_ok=True)
    with open(CONF_PATH, "w") as f:
        f.write("# Generated by dictee-setup\n")
        f.write(f"DICTEE_ASR_BACKEND={asr_backend}\n")
        f.write(f"DICTEE_TRANSLATE_BACKEND={backend}\n")
        f.write(f"DICTEE_LANG_SOURCE={lang_source}\n")
        f.write(f"DICTEE_LANG_TARGET={lang_target}\n")
        f.write(f"DICTEE_CLIPBOARD={'true' if clipboard else 'false'}\n")
        f.write(f"DICTEE_ANIMATION={animation}\n")
        if asr_backend == "vosk":
            f.write(f"DICTEE_VOSK_MODEL={vosk_model}\n")
        elif asr_backend == "whisper":
            f.write(f"DICTEE_WHISPER_MODEL={whisper_model}\n")
            if whisper_lang:
                f.write(f"DICTEE_WHISPER_LANG={whisper_lang}\n")
        if backend == "trans":
            f.write(f"DICTEE_TRANS_ENGINE={trans_engine}\n")
        elif backend == "libretranslate":
            f.write(f"DICTEE_LIBRETRANSLATE_PORT={lt_port}\n")
        elif backend == "ollama":
            f.write(f"DICTEE_OLLAMA_MODEL={ollama_model}\n")
            if ollama_cpu:
                f.write("OLLAMA_NUM_GPU=0\n")


# === Raccourci KDE ===


def qt_key_to_kde(key_sequence):
    """Convertit une QKeySequence en format KDE ('Meta+D')."""
    return key_sequence.toString()


def find_kde_shortcut_for_command(command):
    """Trouve le raccourci KDE existant pour une commande donnée.

    Scanne les .desktop dans ~/.local/share/applications/ pour trouver
    ceux dont Exec correspond, puis lit le raccourci dans kglobalshortcutsrc.
    Retourne (raccourci, nom_desktop) ou (None, None).
    """
    apps_dir = os.path.expanduser("~/.local/share/applications")
    rc_path = os.path.expanduser("~/.config/kglobalshortcutsrc")

    if not os.path.isdir(apps_dir) or not os.path.isfile(rc_path):
        return None, None

    # Trouver les .desktop dont Exec correspond
    matching_desktops = []
    try:
        for fname in os.listdir(apps_dir):
            if not fname.endswith(".desktop"):
                continue
            fpath = os.path.join(apps_dir, fname)
            try:
                with open(fpath) as f:
                    for line in f:
                        if line.strip().startswith("Exec="):
                            exec_cmd = line.strip().split("=", 1)[1].strip()
                            if exec_cmd == command:
                                matching_desktops.append(fname)
                            break
            except OSError:
                continue
    except OSError:
        return None, None

    if not matching_desktops:
        return None, None

    # Lire le raccourci depuis kglobalshortcutsrc
    try:
        with open(rc_path) as f:
            content = f.read()
    except OSError:
        return None, None

    for desktop_name in matching_desktops:
        target = f"[services][{desktop_name}]"
        idx = content.find(target)
        if idx < 0:
            continue
        for line in content[idx + len(target):].split("\n"):
            line = line.strip()
            if not line:
                continue
            if line.startswith("["):
                break
            if line.startswith("_launch="):
                accel = line.split("=", 1)[1].split(",")[0].strip()
                if accel and accel != "none":
                    return accel, desktop_name

    return None, None


def _dictee_desktop_names():
    """Retourne les noms de tous les .desktop qui pointent vers dictee."""
    apps_dir = os.path.expanduser("~/.local/share/applications")
    names = {DICTEE_DESKTOP, DICTEE_TRANSLATE_DESKTOP}
    try:
        for fname in os.listdir(apps_dir):
            if not fname.endswith(".desktop"):
                continue
            try:
                with open(os.path.join(apps_dir, fname)) as f:
                    for line in f:
                        if line.strip().startswith("Exec="):
                            if "/usr/bin/dictee" in line:
                                names.add(fname)
                            break
            except OSError:
                continue
    except OSError:
        pass
    return names


def check_kde_conflict(accel_kde):
    """Vérifie si le raccourci est déjà utilisé dans kglobalshortcutsrc."""
    rc = os.path.expanduser("~/.config/kglobalshortcutsrc")
    if not os.path.isfile(rc):
        return None
    own_desktops = _dictee_desktop_names()
    try:
        with open(rc) as f:
            current_group = ""
            for line in f:
                line = line.strip()
                if line.startswith("[") and line.endswith("]"):
                    current_group = line[1:-1]
                    continue
                if any(d in current_group for d in own_desktops):
                    continue
                if "=" in line:
                    _key, val = line.split("=", 1)
                    parts = val.split(",")
                    if parts and parts[0].strip() == accel_kde:
                        return current_group
    except OSError:
        pass
    return None


def apply_kde_shortcut(accel_kde, desktop_name, command, label, key_sequence=None):
    """Applique le raccourci clavier sous KDE Plasma 6.

    1. Crée le .desktop dans ~/.local/share/applications/
    2. Écrit le raccourci dans kglobalshortcutsrc (persistance)
    3. Enregistre et active via D-Bus kglobalaccel (activation immédiate)
    """
    apps_dir = os.path.expanduser("~/.local/share/applications")
    os.makedirs(apps_dir, exist_ok=True)
    desktop_path = os.path.join(apps_dir, desktop_name)
    with open(desktop_path, "w") as f:
        f.write("[Desktop Entry]\n")
        f.write(f"Exec={command}\n")
        f.write(f"Name={label}\n")
        f.write("NoDisplay=true\n")
        f.write("StartupNotify=false\n")
        f.write("Type=Application\n")
        f.write("X-KDE-GlobalAccel-CommandShortcut=true\n")

    # Écrire le raccourci dans kglobalshortcutsrc (persistance au reboot)
    subprocess.run(
        [
            "kwriteconfig6",
            "--file", "kglobalshortcutsrc",
            "--group", "services",
            "--group", desktop_name,
            "--key", "_launch",
            f"{accel_kde},none,{label}",
        ],
        check=True,
    )
    subprocess.run(
        [
            "kwriteconfig6",
            "--file", "kglobalshortcutsrc",
            "--group", "services",
            "--group", desktop_name,
            "--key", "_k_friendly_name",
            label,
        ],
        check=True,
    )

    # Activer immédiatement via D-Bus kglobalaccel
    if key_sequence is not None:
        _activate_kde_shortcut_dbus(desktop_name, label, key_sequence)

    return accel_kde


def _activate_kde_shortcut_dbus(desktop_name, label, key_sequence):
    """Active un raccourci via D-Bus kglobalaccel (sans redémarrage de session).

    Utilise doRegister + setForeignShortcutKeys pour enregistrer le composant
    et activer la touche immédiatement dans kglobalacceld.
    """
    # Convertir QKeySequence en code Qt int (modifiers | key)
    try:
        combined = key_sequence[0]
        # PyQt6 : QKeyCombination → .toCombined() → int
        if hasattr(combined, "toCombined"):
            qt_key_int = combined.toCombined()
        # PySide6 : déjà int ou enum avec .value
        elif hasattr(combined, "value"):
            qt_key_int = combined.value
        else:
            qt_key_int = int(combined)
    except (IndexError, TypeError):
        return  # Pas de touche valide

    action_id = f"['{desktop_name}', '_launch', '{label}', '{label}']"

    # 1. Enregistrer le composant
    subprocess.run(
        [
            "gdbus", "call", "--session",
            "--dest", "org.kde.kglobalaccel",
            "--object-path", "/kglobalaccel",
            "--method", "org.kde.KGlobalAccel.doRegister",
            action_id,
        ],
        capture_output=True,
    )

    # 2. Affecter la touche
    keys = f"[([{qt_key_int}, 0, 0, 0],)]"
    subprocess.run(
        [
            "gdbus", "call", "--session",
            "--dest", "org.kde.kglobalaccel",
            "--object-path", "/kglobalaccel",
            "--method", "org.kde.KGlobalAccel.setForeignShortcutKeys",
            action_id,
            keys,
        ],
        capture_output=True,
    )


# === Raccourci GNOME ===


def qt_key_to_gnome(key_sequence):
    """Convertit une QKeySequence en format GNOME ('<Super>d')."""
    s = key_sequence.toString()
    s = s.replace("Meta+", "<Super>")
    s = s.replace("Ctrl+", "<Primary>")
    s = s.replace("Alt+", "<Alt>")
    s = s.replace("Shift+", "<Shift>")
    if not s.endswith(">"):
        parts = s.rsplit(">", 1)
        if len(parts) == 2:
            s = parts[0] + ">" + parts[1].lower()
    return s


def apply_gnome_shortcut(accel_gnome):
    """Applique le raccourci clavier sous GNOME/Unity/Cinnamon."""
    schema = "org.gnome.settings-daemon.plugins.media-keys"
    base_path = "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    slot = "dictee"
    path = f"{base_path}/{slot}/"

    try:
        result = subprocess.run(
            ["gsettings", "get", schema, "custom-keybindings"],
            capture_output=True, text=True, check=True,
        )
        current = result.stdout.strip()
        if path not in current:
            if current in ("@as []", "[]"):
                new_list = f"['{path}']"
            else:
                new_list = current.rstrip("]") + f", '{path}']"
            subprocess.run(
                ["gsettings", "set", schema, "custom-keybindings", new_list],
                check=True,
            )
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass

    sub_schema = f"{schema}.custom-keybinding"
    subprocess.run(
        ["gsettings", "set", sub_schema + ":" + path, "name", _("Voice dictation")],
        check=True,
    )
    subprocess.run(
        ["gsettings", "set", sub_schema + ":" + path, "command", DICTEE_COMMAND],
        check=True,
    )
    subprocess.run(
        ["gsettings", "set", sub_schema + ":" + path, "binding", accel_gnome],
        check=True,
    )


# === Ollama helpers ===

# (model_id, label, min_ram_gb, min_vram_gb)
OLLAMA_MODELS = [
    ("translategemma", _("translategemma 4B (3.3 GB, 55 languages, 8 GB RAM)"), 8, 4),
    ("translategemma:12b", _("translategemma 12B (8 GB, best quality, 16 GB RAM)"), 16, 8),
    ("aya:8b", _("aya 8B (5 GB, Cohere, 23 languages, 16 GB RAM)"), 16, 8),
]


def ollama_is_installed():
    """Vérifie si ollama est installé."""
    return shutil.which("ollama") is not None


def get_system_ram_gb():
    """Retourne la RAM totale en Go."""
    try:
        with open("/proc/meminfo") as f:
            for line in f:
                if line.startswith("MemTotal:"):
                    kb = int(line.split()[1])
                    return round(kb / 1024 / 1024, 1)
    except (OSError, ValueError):
        pass
    return 0


def get_gpu_vram_gb():
    """Retourne (VRAM totale, VRAM libre) en Go. (0, 0) si pas de GPU."""
    # NVIDIA
    try:
        result = subprocess.run(
            ["nvidia-smi", "--query-gpu=memory.total,memory.free",
             "--format=csv,noheader,nounits"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0 and result.stdout.strip():
            parts = result.stdout.strip().split("\n")[0].split(",")
            total_mb = int(parts[0].strip())
            free_mb = int(parts[1].strip())
            return round(total_mb / 1024, 1), round(free_mb / 1024, 1)
    except (FileNotFoundError, subprocess.TimeoutExpired, ValueError, IndexError):
        pass
    # AMD
    try:
        import glob
        for path in glob.glob("/sys/class/drm/card*/device/mem_info_vram_total"):
            total = int(open(path).read().strip())
            free_path = path.replace("vram_total", "vram_used")
            used = int(open(free_path).read().strip()) if os.path.exists(free_path) else 0
            total_gb = round(total / 1024**3, 1)
            free_gb = round((total - used) / 1024**3, 1)
            return total_gb, free_gb
    except (OSError, ValueError):
        pass
    return 0, 0


def ollama_list_models():
    """Retourne la liste des modèles ollama installés."""
    try:
        result = subprocess.run(
            ["ollama", "list"], capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0:
            models = []
            for line in result.stdout.strip().split("\n")[1:]:  # skip header
                if line.strip():
                    models.append(line.split()[0].split(":")[0])
            return models
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return []


def ollama_has_model(model_name):
    """Vérifie si un modèle ollama spécifique est installé."""
    installed = ollama_list_models()
    # Normaliser : "translategemma" → "translategemma:latest"
    def _normalize(name):
        return name if ":" in name else name + ":latest"
    target = _normalize(model_name)
    return any(_normalize(m) == target for m in installed)


class OllamaPullThread(QThread):
    """Thread pour télécharger un modèle ollama."""
    finished = Signal(bool, str)
    progress = Signal(str)

    def __init__(self, model_name):
        super().__init__()
        self.model_name = model_name

    def run(self):
        try:
            self.progress.emit(_("Downloading {model}…").format(model=self.model_name))
            result = subprocess.run(
                ["ollama", "pull", self.model_name],
                capture_output=True, text=True, timeout=600,
            )
            if result.returncode == 0:
                self.finished.emit(True, "")
            else:
                self.finished.emit(False, result.stderr.strip() or _("Download failed."))
        except subprocess.TimeoutExpired:
            self.finished.emit(False, _("Download timed out (10 min)."))
        except Exception as e:
            self.finished.emit(False, str(e))


# === Modèles ASR ===

MODEL_DIR = "/usr/share/dictee"
DICTEE_DATA_DIR = os.path.expanduser("~/.local/share/dictee")

# === Backends ASR alternatifs (venvs) ===

VOSK_VENV = os.path.join(DICTEE_DATA_DIR, "vosk-env")
WHISPER_VENV = os.path.join(DICTEE_DATA_DIR, "whisper-env")

VOSK_MODELS = {
    "fr": "vosk-model-small-fr-0.22",
    "en": "vosk-model-small-en-us-0.15",
    "de": "vosk-model-small-de-0.15",
    "es": "vosk-model-small-es-0.42",
    "it": "vosk-model-small-it-0.22",
    "pt": "vosk-model-small-pt-0.3",
    "ru": "vosk-model-small-ru-0.22",
    "zh": "vosk-model-small-cn-0.22",
    "ja": "vosk-model-small-ja-0.22",
}

WHISPER_MODELS = ["tiny", "small", "medium", "large-v3"]


def venv_is_installed(venv_path):
    """Vérifie si un venv Python est installé et contient des packages."""
    site = os.path.join(venv_path, "lib")
    if not os.path.isdir(site):
        return False
    for d in os.listdir(site):
        sp = os.path.join(site, d, "site-packages")
        if os.path.isdir(sp) and len(os.listdir(sp)) > 3:
            return True
    return False


class VenvInstallThread(QThread):
    """Thread pour créer un venv et installer un package pip."""
    finished = Signal(bool, str)
    progress = Signal(str)

    def __init__(self, venv_path, pip_package):
        super().__init__()
        self.venv_path = venv_path
        self.pip_package = pip_package

    def run(self):
        try:
            self.progress.emit(_("Creating virtual environment…"))
            os.makedirs(self.venv_path, exist_ok=True)
            result = subprocess.run(
                ["python3", "-m", "venv", self.venv_path],
                capture_output=True, text=True, timeout=60,
            )
            if result.returncode != 0:
                self.finished.emit(False, result.stderr.strip())
                return
            pip = os.path.join(self.venv_path, "bin", "pip")
            self.progress.emit(_("Installing {pkg}…").format(pkg=self.pip_package))
            result = subprocess.run(
                [pip, "install", "--upgrade", self.pip_package],
                capture_output=True, text=True, timeout=600,
            )
            if result.returncode != 0:
                self.finished.emit(False, result.stderr.strip()[-500:])
                return
            self.finished.emit(True, "")
        except subprocess.TimeoutExpired:
            self.finished.emit(False, _("Installation timed out."))
        except Exception as e:
            self.finished.emit(False, str(e))

ASR_MODELS = [
    {
        "id": "tdt",
        "name": "Parakeet-TDT 0.6B v3",
        "desc": _("Multilingual transcription (25 languages, ~2.5 GB)"),
        "help": _(
            "<b>Parakeet-TDT 0.6B v3</b> — Main transcription model<br><br>"
            "FastConformer encoder + Token-and-Duration Transducer (TDT) decoder.<br>"
            "Supports <b>25 languages</b> including French, English, Spanish, German, etc.<br>"
            "Native punctuation and capitalization (no post-processing needed).<br><br>"
            "<b>Required</b> for all transcription modes (dictation, batch, daemon).<br>"
            "Used by: <code>transcribe</code>, <code>transcribe-daemon</code>, "
            "<code>transcribe-diarize</code>, <code>dictee</code>"
        ),
        "dir": os.path.join(MODEL_DIR, "tdt"),
        "check_file": "encoder-model.onnx",
        "files": [
            ("https://huggingface.co/istupakov/parakeet-tdt-0.6b-v3-onnx/resolve/main/encoder-model.onnx", "encoder-model.onnx"),
            ("https://huggingface.co/istupakov/parakeet-tdt-0.6b-v3-onnx/resolve/main/encoder-model.onnx.data", "encoder-model.onnx.data"),
            ("https://huggingface.co/istupakov/parakeet-tdt-0.6b-v3-onnx/resolve/main/decoder_joint-model.onnx", "decoder_joint-model.onnx"),
            ("https://huggingface.co/istupakov/parakeet-tdt-0.6b-v3-onnx/resolve/main/vocab.txt", "vocab.txt"),
        ],
        "required": True,
    },
    {
        "id": "sortformer",
        "name": "Sortformer",
        "desc": _("Speaker diarization (4 speakers max, ~50 MB)"),
        "help": _(
            "<b>Sortformer</b> — Speaker diarization model<br><br>"
            "Identifies and separates up to <b>4 different speakers</b> in an audio recording.<br>"
            "Labels each transcription segment with the speaker who said it.<br><br>"
            "<b>Optional</b> — only needed if you want speaker identification.<br>"
            "Used by: <code>transcribe-diarize</code>, <code>transcribe-stream-diarize</code>"
        ),
        "dir": os.path.join(MODEL_DIR, "sortformer"),
        "check_file": "diar_streaming_sortformer_4spk-v2.1.onnx",
        "files": [
            ("https://huggingface.co/altunenes/parakeet-rs/resolve/main/diar_streaming_sortformer_4spk-v2.1.onnx", "diar_streaming_sortformer_4spk-v2.1.onnx"),
        ],
        "required": False,
    },
    {
        "id": "nemotron",
        "name": "Nemotron 0.6B",
        "desc": _("English streaming (~2.5 GB)"),
        "help": _(
            "<b>Nemotron 0.6B</b> — English streaming model<br><br>"
            "Optimized for <b>real-time English</b> transcription with low latency.<br>"
            "Processes audio in streaming chunks instead of waiting for the full recording.<br><br>"
            "<b>Optional</b> — only needed for English streaming + diarization mode.<br>"
            "Used by: <code>transcribe-stream-diarize</code>"
        ),
        "dir": os.path.join(MODEL_DIR, "nemotron"),
        "check_file": "encoder.onnx",
        "files": [
            ("https://huggingface.co/altunenes/parakeet-rs/resolve/main/nemotron-speech-streaming-en-0.6b/encoder.onnx", "encoder.onnx"),
            ("https://huggingface.co/altunenes/parakeet-rs/resolve/main/nemotron-speech-streaming-en-0.6b/encoder.onnx.data", "encoder.onnx.data"),
            ("https://huggingface.co/altunenes/parakeet-rs/resolve/main/nemotron-speech-streaming-en-0.6b/decoder_joint.onnx", "decoder_joint.onnx"),
            ("https://huggingface.co/altunenes/parakeet-rs/resolve/main/nemotron-speech-streaming-en-0.6b/tokenizer.model", "tokenizer.model"),
        ],
        "required": False,
    },
]


def model_is_installed(model):
    """Vérifie si un modèle ASR est installé."""
    return os.path.isfile(os.path.join(model["dir"], model["check_file"]))


class ModelDownloadThread(QThread):
    """Thread pour télécharger un modèle ASR."""
    finished = Signal(bool, str)
    progress = Signal(str)

    def __init__(self, model):
        super().__init__()
        self.model = model

    def run(self):
        try:
            model_dir = self.model["dir"]
            os.makedirs(model_dir, exist_ok=True)
            for url, filename in self.model["files"]:
                dest = os.path.join(model_dir, filename)
                if os.path.isfile(dest):
                    continue
                self.progress.emit(_("Downloading {name}…").format(name=filename))
                result = subprocess.run(
                    ["curl", "-L", "--progress-bar", "-o", dest, url],
                    capture_output=True, text=True, timeout=1800,
                )
                if result.returncode != 0:
                    self.finished.emit(False, result.stderr.strip() or _("Download failed."))
                    return
            self.finished.emit(True, "")
        except subprocess.TimeoutExpired:
            self.finished.emit(False, _("Download timed out (30 min)."))
        except PermissionError:
            self.finished.emit(False, _("Permission denied. Run: sudo chmod 777 {dir}").format(
                dir=self.model["dir"]))
        except Exception as e:
            self.finished.emit(False, str(e))


# === LibreTranslate (Docker) ===

LIBRETRANSLATE_IMAGE = "libretranslate/libretranslate"
LIBRETRANSLATE_CONTAINER = "dictee-libretranslate"
LIBRETRANSLATE_PORT = 5000


def docker_is_installed():
    """Vérifie si docker est installé et accessible."""
    return shutil.which("docker") is not None


def docker_is_accessible():
    """Vérifie si l'utilisateur peut exécuter docker (permissions)."""
    try:
        result = subprocess.run(
            ["docker", "info"], capture_output=True, text=True, timeout=5,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def docker_has_image(image=LIBRETRANSLATE_IMAGE):
    """Vérifie si l'image Docker est téléchargée."""
    try:
        result = subprocess.run(
            ["docker", "images", "-q", image],
            capture_output=True, text=True, timeout=5,
        )
        return bool(result.stdout.strip())
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def docker_container_running(name=LIBRETRANSLATE_CONTAINER):
    """Vérifie si le container est en cours d'exécution."""
    try:
        result = subprocess.run(
            ["docker", "inspect", "-f", "{{.State.Running}}", name],
            capture_output=True, text=True, timeout=5,
        )
        return result.stdout.strip() == "true"
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def docker_container_exists(name=LIBRETRANSLATE_CONTAINER):
    """Vérifie si le container existe (arrêté ou en cours)."""
    try:
        result = subprocess.run(
            ["docker", "inspect", name],
            capture_output=True, text=True, timeout=5,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def docker_start_libretranslate(port=LIBRETRANSLATE_PORT, languages="fr,en,es,de"):
    """Démarre le container LibreTranslate."""
    if docker_container_exists():
        # Recréer si le port a changé
        subprocess.run(["docker", "start", LIBRETRANSLATE_CONTAINER],
                       capture_output=True, timeout=10)
    else:
        subprocess.run([
            "docker", "run", "-d",
            "--name", LIBRETRANSLATE_CONTAINER,
            "-p", f"{port}:5000",
            "--restart", "unless-stopped",
            LIBRETRANSLATE_IMAGE,
            "--load-only", languages,
        ], capture_output=True, timeout=30)


def docker_stop_libretranslate():
    """Arrête le container LibreTranslate."""
    subprocess.run(["docker", "stop", LIBRETRANSLATE_CONTAINER],
                   capture_output=True, timeout=15)


class DockerPullThread(QThread):
    """Thread pour télécharger l'image Docker LibreTranslate."""
    finished = Signal(bool, str)
    progress = Signal(str)

    def run(self):
        try:
            self.progress.emit(_("Downloading Docker image…"))
            result = subprocess.run(
                ["docker", "pull", LIBRETRANSLATE_IMAGE],
                capture_output=True, text=True, timeout=600,
            )
            if result.returncode == 0:
                self.finished.emit(True, "")
            else:
                self.finished.emit(False, result.stderr.strip() or _("Download failed."))
        except subprocess.TimeoutExpired:
            self.finished.emit(False, _("Download timed out (10 min)."))
        except Exception as e:
            self.finished.emit(False, str(e))


# === Thread d'installation ===


class InstallThread(QThread):
    finished = Signal(bool, str)
    progress = Signal(str)

    def run(self):
        try:
            if not shutil.which("gh"):
                self.finished.emit(
                    False,
                    _("The 'gh' tool (GitHub CLI) is required.\n"
                      "Install it: sudo apt install gh && gh auth login"),
                )
                return

            tmp_dir = tempfile.mkdtemp(prefix="dictee-setup-")
            is_deb = shutil.which("dpkg") is not None

            if is_deb:
                result = subprocess.run(
                    ["gh", "release", "download", "--repo", ANIMATION_SPEECH_REPO,
                     "--pattern", "*.deb", "--dir", tmp_dir],
                    capture_output=True, text=True,
                )
                if result.returncode != 0:
                    self.finished.emit(False, result.stderr.strip() or _("Download error (.deb)"))
                    return

                debs = [f for f in os.listdir(tmp_dir) if f.endswith(".deb")]
                if not debs:
                    self.finished.emit(False, _("No .deb found in the release."))
                    return

                self.progress.emit(_("Installing…"))
                result = subprocess.run(
                    ["pkexec", "dpkg", "-i", os.path.join(tmp_dir, debs[0])],
                    capture_output=True, text=True,
                )
            else:
                result = subprocess.run(
                    ["gh", "release", "download", "--repo", ANIMATION_SPEECH_REPO,
                     "--pattern", "*.tar.gz", "--dir", tmp_dir],
                    capture_output=True, text=True,
                )
                if result.returncode != 0:
                    self.finished.emit(False, result.stderr.strip() or _("Download error (.tar.gz)"))
                    return

                tarballs = [f for f in os.listdir(tmp_dir) if f.endswith(".tar.gz")]
                if not tarballs:
                    self.finished.emit(False, _("No .tar.gz found in the release."))
                    return

                self.progress.emit(_("Installing…"))
                result = subprocess.run(
                    ["pkexec", "tar", "xzf", os.path.join(tmp_dir, tarballs[0]), "-C", "/usr/local"],
                    capture_output=True, text=True,
                )

            # Nettoyage
            try:
                for f in os.listdir(tmp_dir):
                    os.remove(os.path.join(tmp_dir, f))
                os.rmdir(tmp_dir)
            except OSError:
                pass

            if result.returncode == 0:
                self.finished.emit(True, "")
            else:
                self.finished.emit(False, result.stderr.strip() or _("Installation error."))

        except Exception as e:
            self.finished.emit(False, str(e))


# === Bouton capture raccourci ===


class ShortcutButton(QPushButton):
    """Bouton qui capture une combinaison de touches quand activé."""

    shortcutCaptured = Signal(QKeySequence)

    def __init__(self, parent=None):
        super().__init__(_("Click to capture a shortcut…"), parent)
        self._capturing = False
        self._sequence = None
        self._changed = False
        self.clicked.connect(self._start_capture)

    def _start_capture(self):
        self._capturing = True
        self.setText(_("Press a key combination…"))
        self.setFocus()

    def keyPressEvent(self, event):
        if not self._capturing:
            super().keyPressEvent(event)
            return

        key = event.key()

        # Ignorer les modificateurs seuls
        # PyQt6 : enums scoped (Qt.Key.Key_X), PySide6 : enums flat (Qt.Key_X)
        _Key = getattr(Qt, "Key", Qt)
        if key in (
            _Key.Key_Shift, _Key.Key_Control, _Key.Key_Alt,
            _Key.Key_Meta, _Key.Key_Super_L, _Key.Key_Super_R,
            _Key.Key_AltGr,
        ):
            return

        modifiers = event.modifiers()
        # PyQt6 : .value pour convertir en int, PySide6 : déjà int
        key_int = key.value if hasattr(key, "value") else int(key)
        mod_int = modifiers.value if hasattr(modifiers, "value") else int(modifiers)
        seq = QKeySequence(mod_int | key_int)

        self._capturing = False
        self._sequence = seq
        self._changed = True
        self.setText(_("Shortcut: {label}").format(label=seq.toString(_NATIVE_TEXT)))
        self.shortcutCaptured.emit(seq)

    def sequence(self):
        return self._sequence


# === UI ===


class DicteeSetupDialog(QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowTitle(_("Voice dictation configuration"))
        self.setMinimumWidth(620)
        self.resize(700, 700)
        self.setWindowIcon(QIcon.fromTheme("audio-input-microphone"))
        self.de_name, self.de_type = detect_desktop()
        self._install_thread = None

        self.conf = load_config()
        conf = self.conf

        outer_layout = QVBoxLayout(self)
        outer_layout.setContentsMargins(0, 0, 0, 0)
        outer_layout.setSpacing(0)

        # -- Scroll area --
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QFrame.Shape.NoFrame)
        content = QWidget()
        layout = QVBoxLayout(content)
        layout.setSpacing(16)
        layout.setContentsMargins(20, 20, 20, 16)

        self._model_widgets = {}
        self._model_threads = {}

        # -- Section raccourci --
        grp_shortcut = QGroupBox(_("Keyboard shortcut"))
        lay_sc = QVBoxLayout(grp_shortcut)
        lay_sc.setSpacing(8)
        lay_sc.setContentsMargins(16, 16, 16, 12)

        lbl_de = QLabel(_("Detected environment: <b>{name}</b>").format(name=self.de_name))
        lay_sc.addWidget(lbl_de)

        if self.de_type in ("kde", "gnome"):
            # Raccourci dictée
            lbl_dictee = QLabel(_("Voice dictation") + " :")
            lay_sc.addWidget(lbl_dictee)
            self.btn_capture = ShortcutButton()
            self._dictee_existing_desktop = None
            if self.de_type == "kde":
                existing, desktop = find_kde_shortcut_for_command(DICTEE_COMMAND)
                if existing:
                    seq = QKeySequence.fromString(existing)
                    self.btn_capture._sequence = seq
                    self.btn_capture.setText(_("Shortcut: {label}").format(
                        label=seq.toString(_NATIVE_TEXT)))
                    self._dictee_existing_desktop = desktop
            lay_sc.addWidget(self.btn_capture)

            self.lbl_conflict = QLabel()
            self.lbl_conflict.setVisible(False)
            lay_sc.addWidget(self.lbl_conflict)
            self.btn_capture.shortcutCaptured.connect(self._on_shortcut_captured)

            lay_sc.addSpacing(4)

            # Raccourci traduction
            lbl_translate = QLabel(_("Dictation + Translation") + " :")
            lay_sc.addWidget(lbl_translate)
            self.btn_capture_translate = ShortcutButton()
            self._translate_existing_desktop = None
            if self.de_type == "kde":
                existing_tr, desktop_tr = find_kde_shortcut_for_command(DICTEE_TRANSLATE_COMMAND)
                if existing_tr:
                    seq_tr = QKeySequence.fromString(existing_tr)
                    self.btn_capture_translate._sequence = seq_tr
                    self.btn_capture_translate.setText(_("Shortcut: {label}").format(
                        label=seq_tr.toString(_NATIVE_TEXT)))
                    self._translate_existing_desktop = desktop_tr
            lay_sc.addWidget(self.btn_capture_translate)

            self.lbl_conflict_translate = QLabel()
            self.lbl_conflict_translate.setVisible(False)
            lay_sc.addWidget(self.lbl_conflict_translate)
            self.btn_capture_translate.shortcutCaptured.connect(self._on_shortcut_translate_captured)
        else:
            lbl_unsup = QLabel(
                "<i>" + _(
                    "Unsupported environment for automatic configuration.\n"
                    "Configure the shortcut manually in your window manager:\n"
                    "Command: <b>{cmd}</b>"
                ).format(cmd=DICTEE_COMMAND).replace("\n", "<br>") + "</i>"
            )
            lbl_unsup.setWordWrap(True)
            lay_sc.addWidget(lbl_unsup)

        # -- Section backend ASR --
        grp_asr = QGroupBox(_("ASR backend"))
        lay_asr = QVBoxLayout(grp_asr)
        lay_asr.setSpacing(8)
        lay_asr.setContentsMargins(16, 16, 16, 12)

        current_asr = self.conf.get("DICTEE_ASR_BACKEND", "parakeet")

        self.asr_group = QButtonGroup(self)
        self._venv_threads = {}

        # Parakeet-TDT (toujours disponible si modèle installé)
        self.rb_parakeet = QRadioButton("Parakeet-TDT 0.6B — " + _("multilingual, 25 languages (installed with .deb)"))
        self.rb_parakeet.setChecked(current_asr == "parakeet")
        self.asr_group.addButton(self.rb_parakeet)
        lay_asr.addWidget(self.rb_parakeet)

        # Modèles Parakeet (indentés sous le radio)
        for model in ASR_MODELS:
            row = QHBoxLayout()
            row.setSpacing(8)
            row.setContentsMargins(24, 0, 0, 0)

            installed = model_is_installed(model)
            required = _(" (required)") if model["required"] else ""

            lbl = QLabel()
            icon = '<span style="color: green;">✓</span>' if installed \
                else '<span style="color: orange;">⚠</span>'
            line2 = model["desc"] + (required if not installed else "")
            lbl.setText(f'{icon} {model["name"]}<br>'
                        f'<span style="font-size: 9.5pt; color: gray;">{line2}</span>')
            lbl.setWordWrap(True)
            row.addWidget(lbl, 1)

            btn_info = QPushButton("?")
            btn_info.setFixedSize(24, 24)
            btn_info.setToolTip(model["help"])
            btn_info.setStyleSheet("font-weight: bold; border-radius: 12px;")
            btn_info.clicked.connect(lambda checked, m=model: QMessageBox.information(
                self, m["name"], m["help"]))
            row.addWidget(btn_info)

            btn = QPushButton(_("Download") if not installed else _("Installed"))
            btn.setEnabled(not installed)
            btn.setFixedWidth(120)
            row.addWidget(btn)

            lay_asr.addLayout(row)

            progress = QProgressBar()
            progress.setRange(0, 0)
            progress.setVisible(False)
            lay_asr.addWidget(progress)

            self._model_widgets[model["id"]] = {"label": lbl, "button": btn, "progress": progress, "model": model}
            btn.clicked.connect(lambda checked, m=model: self._on_model_download(m))

        # Vosk
        row_vosk = QHBoxLayout()
        self.rb_vosk = QRadioButton("Vosk — " + _("lightweight, streaming (~50 MB)"))
        self.rb_vosk.setChecked(current_asr == "vosk")
        self.asr_group.addButton(self.rb_vosk)
        row_vosk.addWidget(self.rb_vosk, 1)

        vosk_installed = venv_is_installed(VOSK_VENV)
        self.btn_install_vosk = QPushButton(_("Installed") if vosk_installed else _("Install"))
        self.btn_install_vosk.setEnabled(not vosk_installed)
        self.btn_install_vosk.setFixedWidth(120)
        self.btn_install_vosk.clicked.connect(lambda: self._install_venv("vosk", VOSK_VENV, "vosk"))
        row_vosk.addWidget(self.btn_install_vosk)
        lay_asr.addLayout(row_vosk)

        # Sous-options Vosk : choix de langue
        self.w_vosk_options = QWidget()
        vosk_lay = QHBoxLayout(self.w_vosk_options)
        vosk_lay.setContentsMargins(24, 0, 0, 0)
        lbl_vosk_lang = QLabel(_("Language:"))
        self.cmb_vosk_lang = QComboBox()
        for code, name in VOSK_MODELS.items():
            self.cmb_vosk_lang.addItem(f"{code} — {name}", code)
        cur_vosk = self.conf.get("DICTEE_VOSK_MODEL", "fr")
        idx = self.cmb_vosk_lang.findData(cur_vosk)
        if idx >= 0:
            self.cmb_vosk_lang.setCurrentIndex(idx)
        vosk_lay.addWidget(lbl_vosk_lang)
        vosk_lay.addWidget(self.cmb_vosk_lang)
        vosk_lay.addStretch()
        self.w_vosk_options.setVisible(current_asr == "vosk")
        lay_asr.addWidget(self.w_vosk_options)

        # faster-whisper
        row_whisper = QHBoxLayout()
        self.rb_whisper = QRadioButton("faster-whisper — " + _("99 languages, auto-detect (CTranslate2)"))
        self.rb_whisper.setChecked(current_asr == "whisper")
        self.asr_group.addButton(self.rb_whisper)
        row_whisper.addWidget(self.rb_whisper, 1)

        whisper_installed = venv_is_installed(WHISPER_VENV)
        self.btn_install_whisper = QPushButton(_("Installed") if whisper_installed else _("Install"))
        self.btn_install_whisper.setEnabled(not whisper_installed)
        self.btn_install_whisper.setFixedWidth(120)
        self.btn_install_whisper.clicked.connect(lambda: self._install_venv("whisper", WHISPER_VENV, "faster-whisper"))
        row_whisper.addWidget(self.btn_install_whisper)
        lay_asr.addLayout(row_whisper)

        # Sous-options Whisper : choix modèle + langue
        self.w_whisper_options = QWidget()
        whisper_lay = QHBoxLayout(self.w_whisper_options)
        whisper_lay.setContentsMargins(24, 0, 0, 0)
        lbl_wh_model = QLabel(_("Model:"))
        self.cmb_whisper_model = QComboBox()
        for m in WHISPER_MODELS:
            self.cmb_whisper_model.addItem(m)
        cur_wh = self.conf.get("DICTEE_WHISPER_MODEL", "small")
        idx = self.cmb_whisper_model.findText(cur_wh)
        if idx >= 0:
            self.cmb_whisper_model.setCurrentIndex(idx)
        whisper_lay.addWidget(lbl_wh_model)
        whisper_lay.addWidget(self.cmb_whisper_model)
        lbl_wh_lang = QLabel(_("Language:"))
        self.txt_whisper_lang = QComboBox()
        self.txt_whisper_lang.setEditable(True)
        self.txt_whisper_lang.addItems(["", "fr", "en", "es", "de", "it", "pt", "ru", "zh", "ja", "ko", "ar"])
        cur_wl = self.conf.get("DICTEE_WHISPER_LANG", "")
        self.txt_whisper_lang.setCurrentText(cur_wl)
        whisper_lay.addWidget(lbl_wh_lang)
        whisper_lay.addWidget(self.txt_whisper_lang)
        lbl_auto = QLabel(_("(empty = auto-detect)"))
        lbl_auto.setStyleSheet("color: gray;")
        whisper_lay.addWidget(lbl_auto)
        whisper_lay.addStretch()
        self.w_whisper_options.setVisible(current_asr == "whisper")
        lay_asr.addWidget(self.w_whisper_options)

        # Afficher/masquer les sous-options selon le backend sélectionné
        def _on_asr_toggled():
            self.w_vosk_options.setVisible(self.rb_vosk.isChecked())
            self.w_whisper_options.setVisible(self.rb_whisper.isChecked())
        self.rb_parakeet.toggled.connect(lambda: _on_asr_toggled())
        self.rb_vosk.toggled.connect(lambda: _on_asr_toggled())
        self.rb_whisper.toggled.connect(lambda: _on_asr_toggled())

        layout.addWidget(grp_asr)

        layout.addWidget(grp_shortcut)

        # -- Section traduction --
        grp_translate = QGroupBox()
        lay_tr_title = QHBoxLayout()
        lay_tr_title.setContentsMargins(0, 0, 0, 0)
        lay_tr_title.setSpacing(6)
        lbl_tr_title = QLabel("<b>" + _("Translation") + "</b>")
        lay_tr_title.addWidget(lbl_tr_title)
        btn_help_tr = QPushButton("?")
        btn_help_tr.setFixedSize(22, 22)
        btn_help_tr.setToolTip(
            _("How to translate:") + "\n\n"
            + _("• Keyboard shortcut: configure above (Dictation + Translation)") + "\n"
            + _("• Plasmoid: long press or translation button") + "\n"
            + _("• CLI: dictee --translate") + "\n"
            + _("• Direct: transcribe-client | trans -b :en")
        )
        lay_tr_title.addWidget(btn_help_tr)
        lay_tr_title.addStretch()

        lay_tr = QVBoxLayout(grp_translate)
        lay_tr.setSpacing(6)
        lay_tr.setContentsMargins(16, 16, 16, 12)
        lay_tr.addLayout(lay_tr_title)

        # Langues
        form_lang = QFormLayout()
        form_lang.setHorizontalSpacing(12)
        form_lang.setVerticalSpacing(8)

        self.combo_src = QComboBox()
        self.combo_tgt = QComboBox()
        for code, name in LANGUAGES:
            self.combo_src.addItem(f"{code} — {name}", code)
            self.combo_tgt.addItem(f"{code} — {name}", code)

        default_src = conf.get("DICTEE_LANG_SOURCE", self._system_lang())
        default_tgt = conf.get("DICTEE_LANG_TARGET", "en")
        self._set_combo_by_data(self.combo_src, default_src, 0)
        self._set_combo_by_data(self.combo_tgt, default_tgt, 1)

        form_lang.addRow(_("Source language:"), self.combo_src)
        form_lang.addRow(_("Target language:"), self.combo_tgt)
        lay_tr.addLayout(form_lang)

        lay_tr.addSpacing(4)

        # Backend radio buttons
        lbl_backend = QLabel(_("Backend:"))
        lay_tr.addWidget(lbl_backend)

        self.radio_trans = QRadioButton(_("translate-shell"))
        self.radio_libretranslate = QRadioButton(_("LibreTranslate (local, Docker)"))
        self.radio_ollama = QRadioButton(_("ollama (100% local)"))
        self.radio_trans.setChecked(True)

        self.btn_group_backend = QButtonGroup(self)
        self.btn_group_backend.addButton(self.radio_trans)
        self.btn_group_backend.addButton(self.radio_libretranslate)
        self.btn_group_backend.addButton(self.radio_ollama)

        for radio in (self.radio_trans, self.radio_libretranslate, self.radio_ollama):
            radio.setContentsMargins(16, 0, 0, 0)
            lay_tr.addWidget(radio)

        # translate-shell engine selection
        self.trans_widget = QFrame()
        lay_trans = QHBoxLayout(self.trans_widget)
        lay_trans.setContentsMargins(32, 4, 0, 0)
        lay_trans.setSpacing(8)
        lbl_engine = QLabel(_("Engine:"))
        self.combo_trans_engine = QComboBox()
        for eid, elabel in [
            ("google", "Google Translate"),
            ("bing", "Bing"),
        ]:
            self.combo_trans_engine.addItem(elabel, eid)
        default_engine = conf.get("DICTEE_TRANS_ENGINE", "google")
        self._set_combo_by_data(self.combo_trans_engine, default_engine, 0)
        lay_trans.addWidget(lbl_engine)
        lay_trans.addWidget(self.combo_trans_engine, 1)
        lay_tr.addWidget(self.trans_widget)

        self.radio_trans.toggled.connect(lambda checked: self.trans_widget.setVisible(checked))
        self.trans_widget.setVisible(self.radio_trans.isChecked())

        # LibreTranslate (Docker) widget
        self.lt_widget = QFrame()
        lay_lt = QVBoxLayout(self.lt_widget)
        lay_lt.setContentsMargins(32, 4, 0, 0)
        lay_lt.setSpacing(4)

        lay_lt_port = QHBoxLayout()
        lay_lt_port.setSpacing(8)
        lbl_lt_port = QLabel(_("Port:"))
        lay_lt_port.addWidget(lbl_lt_port)
        self.spin_lt_port = QComboBox()
        self.spin_lt_port.setEditable(True)
        for p in ("5000", "5001", "5002", "8080"):
            self.spin_lt_port.addItem(p)
        default_port = str(conf.get("DICTEE_LIBRETRANSLATE_PORT", "5000"))
        idx = self.spin_lt_port.findText(default_port)
        if idx >= 0:
            self.spin_lt_port.setCurrentIndex(idx)
        else:
            self.spin_lt_port.setCurrentText(default_port)
        lay_lt_port.addWidget(self.spin_lt_port)
        lay_lt_port.addStretch()
        lay_lt.addLayout(lay_lt_port)

        self.lbl_lt_status = QLabel()
        self.lbl_lt_status.setWordWrap(True)
        lay_lt.addWidget(self.lbl_lt_status)

        lay_lt_buttons = QHBoxLayout()
        lay_lt_buttons.setSpacing(8)

        self.btn_lt_pull = QPushButton(_("Download image"))
        self.btn_lt_pull.setVisible(False)
        self.btn_lt_pull.clicked.connect(self._on_lt_pull)
        lay_lt_buttons.addWidget(self.btn_lt_pull)

        self.btn_lt_start = QPushButton(_("Start"))
        self.btn_lt_start.setVisible(False)
        self.btn_lt_start.clicked.connect(self._on_lt_start)
        lay_lt_buttons.addWidget(self.btn_lt_start)

        self.btn_lt_stop = QPushButton(_("Stop"))
        self.btn_lt_stop.setVisible(False)
        self.btn_lt_stop.clicked.connect(self._on_lt_stop)
        lay_lt_buttons.addWidget(self.btn_lt_stop)

        lay_lt_buttons.addStretch()
        lay_lt.addLayout(lay_lt_buttons)

        self.progress_lt = QProgressBar()
        self.progress_lt.setRange(0, 0)
        self.progress_lt.setVisible(False)
        lay_lt.addWidget(self.progress_lt)

        lay_tr.addWidget(self.lt_widget)

        self.radio_libretranslate.toggled.connect(self._on_lt_toggled)
        self.lt_widget.setVisible(False)
        self._docker_pull_thread = None

        # Ollama model selection + status
        self.ollama_widget = QFrame()
        lay_ollama = QVBoxLayout(self.ollama_widget)
        lay_ollama.setContentsMargins(32, 4, 0, 0)
        lay_ollama.setSpacing(4)

        lay_model = QHBoxLayout()
        lay_model.setSpacing(8)
        lbl_model = QLabel(_("Model:"))
        self.combo_ollama_model = QComboBox()
        for model_id, model_label, _ram, _vram in OLLAMA_MODELS:
            self.combo_ollama_model.addItem(model_label, model_id)
        default_model = conf.get("DICTEE_OLLAMA_MODEL", "translategemma")
        self._set_combo_by_data(self.combo_ollama_model, default_model, 0)
        lay_model.addWidget(lbl_model)
        lay_model.addWidget(self.combo_ollama_model, 1)
        lay_ollama.addLayout(lay_model)

        self.lbl_ollama_status = QLabel()
        self.lbl_ollama_status.setWordWrap(True)
        lay_ollama.addWidget(self.lbl_ollama_status)

        self.chk_ollama_cpu = QCheckBox(_("Force CPU (OLLAMA_NUM_GPU=0)"))
        self.chk_ollama_cpu.setVisible(False)
        self.chk_ollama_cpu.setChecked(conf.get("OLLAMA_NUM_GPU") == "0")
        self.chk_ollama_cpu.setToolTip(
            _("Use CPU instead of GPU for ollama inference (slower but no VRAM needed)"))
        lay_ollama.addWidget(self.chk_ollama_cpu)

        self.btn_ollama_pull = QPushButton(_("Download model"))
        self.btn_ollama_pull.setVisible(False)
        self.btn_ollama_pull.clicked.connect(self._on_ollama_pull)
        lay_ollama.addWidget(self.btn_ollama_pull)

        self.progress_ollama = QProgressBar()
        self.progress_ollama.setRange(0, 0)
        self.progress_ollama.setVisible(False)
        lay_ollama.addWidget(self.progress_ollama)

        lay_tr.addWidget(self.ollama_widget)

        # Connect signals
        self.radio_ollama.toggled.connect(self._on_backend_toggled)
        self.combo_ollama_model.currentIndexChanged.connect(self._on_ollama_model_changed)
        self._ollama_pull_thread = None

        saved_backend = conf.get("DICTEE_TRANSLATE_BACKEND", "trans")
        if saved_backend == "ollama":
            self.radio_ollama.setChecked(True)
        elif saved_backend == "libretranslate":
            self.radio_libretranslate.setChecked(True)

        # Initial state
        self._on_backend_toggled(self.radio_ollama.isChecked())
        self._on_lt_toggled(self.radio_libretranslate.isChecked())

        layout.addWidget(grp_translate)

        # -- Section options --
        grp_options = QGroupBox(_("Options"))
        lay_opt = QVBoxLayout(grp_options)
        lay_opt.setSpacing(6)
        lay_opt.setContentsMargins(16, 16, 16, 12)

        self.chk_clipboard = QCheckBox(_("Copy transcription to clipboard"))
        self.chk_clipboard.setChecked(conf.get("DICTEE_CLIPBOARD", "true") == "true")
        lay_opt.addWidget(self.chk_clipboard)

        layout.addWidget(grp_options)

        # -- Section retour visuel --
        grp_visual = QGroupBox(_("Visual feedback"))
        lay_vis = QVBoxLayout(grp_visual)
        lay_vis.setSpacing(6)
        lay_vis.setContentsMargins(16, 16, 16, 12)

        self.chk_anim_speech = QCheckBox(_("animation-speech (overlay)"))
        self.chk_plasmoid = QCheckBox(_("KDE Plasma widget (panel)"))
        self.chk_gnome_ext = QCheckBox(_("GNOME Shell extension (not yet available)"))
        self.chk_gnome_ext.setEnabled(False)

        # Charger l'état depuis la config
        anim = conf.get("DICTEE_ANIMATION", "speech")
        self.chk_anim_speech.setChecked(anim in ("speech", "both"))
        self.chk_plasmoid.setChecked(anim in ("plasmoid", "both"))

        lay_vis.addWidget(self.chk_anim_speech)
        lay_vis.addWidget(self.chk_plasmoid)
        lay_vis.addWidget(self.chk_gnome_ext)

        # Status et installation
        self.lbl_anim_status = QLabel()
        self.lbl_anim_status.setWordWrap(True)
        lay_vis.addWidget(self.lbl_anim_status)

        self.btn_install_anim = QPushButton(_("Install animation-speech"))
        self.btn_install_anim.setVisible(False)
        self.btn_install_anim.clicked.connect(self._on_install_animation)
        lay_vis.addWidget(self.btn_install_anim)

        self.progress_anim = QProgressBar()
        self.progress_anim.setRange(0, 0)
        self.progress_anim.setVisible(False)
        lay_vis.addWidget(self.progress_anim)

        self._check_animation_speech()

        layout.addWidget(grp_visual)

        # -- Section services --
        grp_services = QGroupBox(_("Startup services"))
        lay_srv = QVBoxLayout(grp_services)
        lay_srv.setSpacing(6)
        lay_srv.setContentsMargins(16, 16, 16, 12)

        self.chk_daemon = QCheckBox(_("Start transcription daemon at startup"))
        self.chk_tray = QCheckBox(_("Show notification area icon"))

        # Lire l'état réel des services systemd
        self.chk_daemon.setChecked(self._is_service_enabled("dictee"))
        self.chk_tray.setChecked(self._is_service_enabled("dictee-tray"))

        lay_srv.addWidget(self.chk_daemon)
        lay_srv.addWidget(self.chk_tray)

        layout.addWidget(grp_services)

        layout.addStretch()
        scroll.setWidget(content)
        outer_layout.addWidget(scroll, 1)

        # -- Boutons (hors scroll) --
        lay_buttons = QHBoxLayout()
        lay_buttons.setContentsMargins(20, 8, 20, 16)
        lay_buttons.addStretch()

        btn_cancel = QPushButton(_("Cancel"))
        btn_cancel.clicked.connect(self.reject)
        lay_buttons.addWidget(btn_cancel)

        lay_buttons.addSpacing(8)

        btn_apply = QPushButton(_("Apply"))
        btn_apply.clicked.connect(self._on_apply)
        lay_buttons.addWidget(btn_apply)

        lay_buttons.addSpacing(8)

        btn_ok = QPushButton(_("OK"))
        btn_ok.setDefault(True)
        btn_ok.clicked.connect(self._on_ok)
        lay_buttons.addWidget(btn_ok)

        outer_layout.addLayout(lay_buttons)

        # Hauteur max = contenu complet + boutons (pas de scroll inutile)
        content_h = content.sizeHint().height()
        buttons_h = lay_buttons.sizeHint().height() if hasattr(lay_buttons, 'sizeHint') else 50
        self.setMaximumHeight(content_h + buttons_h + 10)

    @staticmethod
    def _is_service_enabled(name):
        """Vérifie si un service systemd user est enabled."""
        try:
            result = subprocess.run(
                ["systemctl", "--user", "is-enabled", name],
                capture_output=True, text=True,
            )
            return result.stdout.strip() == "enabled"
        except (FileNotFoundError, subprocess.CalledProcessError):
            return False

    @staticmethod
    def _system_lang():
        lang = os.environ.get("LANG", "")
        if lang:
            return lang.split("_")[0].split(".")[0]
        try:
            return locale.getdefaultlocale()[0].split("_")[0]
        except (AttributeError, IndexError):
            return "fr"

    @staticmethod
    def _set_combo_by_data(combo, data, fallback_idx):
        for i in range(combo.count()):
            if combo.itemData(i) == data:
                combo.setCurrentIndex(i)
                return
        combo.setCurrentIndex(fallback_idx)

    # -- Capture raccourci --

    def _check_conflict(self, seq, lbl_conflict):
        if self.de_type == "kde":
            accel_kde = qt_key_to_kde(seq)
            conflict = check_kde_conflict(accel_kde)
            if conflict:
                lbl_conflict.setText(
                    '<span style="color: orange;">⚠ ' +
                    _("Shortcut already used by '{name}'").format(name=conflict) +
                    '</span>'
                )
                lbl_conflict.setVisible(True)
            else:
                lbl_conflict.setVisible(False)

    # -- Ollama backend --

    def _on_backend_toggled(self, ollama_checked):
        self.ollama_widget.setVisible(ollama_checked)
        if ollama_checked:
            self._check_ollama_status()

    def _on_ollama_model_changed(self, _index):
        if self.radio_ollama.isChecked():
            self._check_ollama_status()

    def _check_ollama_status(self):
        if not ollama_is_installed():
            self.lbl_ollama_status.setText(
                '<span style="color: red;">⚠ ' +
                _("ollama is not installed") + '</span><br>'
                '<small><a href="https://ollama.com">https://ollama.com</a></small>'
            )
            self.lbl_ollama_status.setOpenExternalLinks(True)
            self.btn_ollama_pull.setVisible(False)
            return

        model = self.combo_ollama_model.currentData()

        # Trouver les seuils RAM/VRAM pour ce modèle
        min_ram = 8
        min_vram = 4
        for m_id, _label, m_ram, m_vram in OLLAMA_MODELS:
            if m_id == model:
                min_ram, min_vram = m_ram, m_vram
                break

        # Détecter la config système
        sys_ram = get_system_ram_gb()
        vram_total, vram_free = get_gpu_vram_gb()
        warnings = []
        if sys_ram and sys_ram < min_ram:
            warnings.append(
                '<span style="color: orange;">⚠ ' +
                _("RAM: {actual} GB / {required} GB recommended").format(
                    actual=sys_ram, required=min_ram) +
                '</span>')
        vram_insufficient = False
        if vram_total:
            # Comparer la VRAM libre (pas totale) — Parakeet occupe ~3 Go
            if vram_free < min_vram:
                vram_insufficient = True
                warnings.append(
                    '<span style="color: orange;">⚠ ' +
                    _("VRAM free: {free} GB / {required} GB required (total: {total} GB)").format(
                        free=vram_free, required=min_vram, total=vram_total) +
                    '</span>')
        else:
            vram_insufficient = True
            warnings.append(
                '<small><i>' +
                _("No GPU detected — ollama will use CPU (slower).") +
                '</i></small>')

        # Proposer le mode CPU si VRAM insuffisante ou absente
        self.chk_ollama_cpu.setVisible(vram_insufficient)
        if vram_insufficient and not vram_total:
            # Pas de GPU → forcer CPU automatiquement
            self.chk_ollama_cpu.setChecked(True)

        hw_info = ""
        if warnings:
            hw_info = "<br>" + "<br>".join(warnings)

        if ollama_has_model(model):
            self.lbl_ollama_status.setText(
                '<span style="color: green;">✓ ' +
                _("Model {model} ready").format(model=model) + '</span>' +
                hw_info
            )
            self.btn_ollama_pull.setVisible(False)
        else:
            self.lbl_ollama_status.setText(
                '<span style="color: orange;">⚠ ' +
                _("Model {model} not downloaded").format(model=model) + '</span>' +
                hw_info
            )
            self.btn_ollama_pull.setVisible(True)
            self.btn_ollama_pull.setText(_("Download model"))
            self.btn_ollama_pull.setEnabled(True)

    def _on_ollama_pull(self):
        model = self.combo_ollama_model.currentData()
        self.btn_ollama_pull.setEnabled(False)
        self.progress_ollama.setVisible(True)

        self._ollama_pull_thread = OllamaPullThread(model)
        self._ollama_pull_thread.progress.connect(
            lambda text: self.btn_ollama_pull.setText(text))
        self._ollama_pull_thread.finished.connect(self._on_ollama_pull_finished)
        self._ollama_pull_thread.start()

    def _on_ollama_pull_finished(self, success, message):
        self.progress_ollama.setVisible(False)
        if success:
            self._check_ollama_status()
        else:
            self.btn_ollama_pull.setText(_("Download model"))
            self.btn_ollama_pull.setEnabled(True)
            QMessageBox.critical(self, _("Download error"), message)

    # -- LibreTranslate backend --

    def _on_lt_toggled(self, checked):
        self.lt_widget.setVisible(checked)
        if checked:
            self._check_lt_status()

    def _check_lt_status(self):
        if not docker_is_installed():
            self.lbl_lt_status.setText(
                '<span style="color: red;">⚠ ' +
                _("Docker is not installed") + '</span><br>'
                '<small>sudo apt install docker.io</small>'
            )
            self.btn_lt_pull.setVisible(False)
            self.btn_lt_start.setVisible(False)
            self.btn_lt_stop.setVisible(False)
            return

        if not docker_is_accessible():
            self.lbl_lt_status.setText(
                '<span style="color: red;">⚠ ' +
                _("Docker permission denied") + '</span><br>'
                '<small>sudo usermod -aG docker $USER ' +
                _("(then log out and back in)") + '</small>'
            )
            self.btn_lt_pull.setVisible(False)
            self.btn_lt_start.setVisible(False)
            self.btn_lt_stop.setVisible(False)
            return

        if not docker_has_image():
            self.lbl_lt_status.setText(
                '<span style="color: orange;">⚠ ' +
                _("Docker image not downloaded (~2 GB)") + '</span>'
            )
            self.btn_lt_pull.setVisible(True)
            self.btn_lt_pull.setEnabled(True)
            self.btn_lt_start.setVisible(False)
            self.btn_lt_stop.setVisible(False)
            return

        if docker_container_running():
            port = self.spin_lt_port.currentText()
            self.lbl_lt_status.setText(
                '<span style="color: green;">✓ ' +
                _("LibreTranslate running on port {port}").format(port=port) + '</span>'
            )
            self.btn_lt_pull.setVisible(False)
            self.btn_lt_start.setVisible(False)
            self.btn_lt_stop.setVisible(True)
        else:
            self.lbl_lt_status.setText(
                '<span style="color: orange;">⚠ ' +
                _("LibreTranslate stopped") + '</span>'
            )
            self.btn_lt_pull.setVisible(False)
            self.btn_lt_start.setVisible(True)
            self.btn_lt_stop.setVisible(False)

    def _on_lt_pull(self):
        self.btn_lt_pull.setEnabled(False)
        self.progress_lt.setVisible(True)

        self._docker_pull_thread = DockerPullThread()
        self._docker_pull_thread.progress.connect(
            lambda text: self.btn_lt_pull.setText(text))
        self._docker_pull_thread.finished.connect(self._on_lt_pull_finished)
        self._docker_pull_thread.start()

    def _on_lt_pull_finished(self, success, message):
        self.progress_lt.setVisible(False)
        if success:
            self._check_lt_status()
        else:
            self.btn_lt_pull.setText(_("Download image"))
            self.btn_lt_pull.setEnabled(True)
            QMessageBox.critical(self, _("Download error"), message)

    def _on_lt_start(self):
        try:
            port = int(self.spin_lt_port.currentText())
            docker_start_libretranslate(port=port)
        except Exception as e:
            QMessageBox.critical(self, _("Error"), str(e))
        self._check_lt_status()

    def _on_lt_stop(self):
        try:
            docker_stop_libretranslate()
        except Exception as e:
            QMessageBox.critical(self, _("Error"), str(e))
        self._check_lt_status()

    # -- Modèles ASR --

    def _on_model_download(self, model):
        mid = model["id"]
        w = self._model_widgets[mid]
        w["button"].setEnabled(False)
        w["progress"].setVisible(True)

        thread = ModelDownloadThread(model)
        thread.progress.connect(lambda text, _m=mid: self._model_widgets[_m]["button"].setText(text))
        thread.finished.connect(lambda ok, msg, _m=mid: self._on_model_download_finished(_m, ok, msg))
        self._model_threads[mid] = thread
        thread.start()

    def _on_model_download_finished(self, mid, success, message):
        w = self._model_widgets[mid]
        w["progress"].setVisible(False)
        model = w["model"]
        if success:
            w["button"].setText(_("Installed"))
            w["button"].setEnabled(False)
            w["label"].setText(f'<span style="color: green;">✓</span> {model["name"]}<br>'
                               f'<span style="font-size: 9.5pt; color: gray;">{model["desc"]}</span>')
        else:
            w["button"].setText(_("Download"))
            w["button"].setEnabled(True)
            QMessageBox.critical(self, _("Download error"), message)

    # -- Installation venv ASR --

    def _install_venv(self, name, venv_path, pip_package):
        btn = self.btn_install_vosk if name == "vosk" else self.btn_install_whisper
        btn.setEnabled(False)
        btn.setText(_("Installing…"))
        thread = VenvInstallThread(venv_path, pip_package)
        thread.progress.connect(lambda text: btn.setText(text))
        thread.finished.connect(lambda ok, msg, n=name: self._on_venv_installed(n, ok, msg))
        self._venv_threads[name] = thread
        thread.start()

    def _on_venv_installed(self, name, success, message):
        btn = self.btn_install_vosk if name == "vosk" else self.btn_install_whisper
        if success:
            btn.setText(_("Installed"))
            btn.setEnabled(False)
        else:
            btn.setText(_("Install"))
            btn.setEnabled(True)
            QMessageBox.critical(self, _("Installation error"), message)

    # -- Capture raccourci --

    def _on_shortcut_captured(self, seq):
        self._check_conflict(seq, self.lbl_conflict)

    def _on_shortcut_translate_captured(self, seq):
        self._check_conflict(seq, self.lbl_conflict_translate)

    # -- Animation-speech --

    def _check_animation_speech(self):
        parts = []
        has_anim = shutil.which(ANIMATION_SPEECH_BIN)
        if has_anim:
            try:
                result = subprocess.run(
                    ["dpkg-query", "-W", "-f", "${Version}", "animation-speech"],
                    capture_output=True, text=True,
                )
                v = result.stdout.strip() if result.returncode == 0 else ""
                if v:
                    parts.append('<span style="color: green;">' +
                                 _("animation-speech {version} installed").format(version=v) +
                                 '</span>')
                else:
                    parts.append('<span style="color: green;">' +
                                 _("animation-speech installed") + '</span>')
            except FileNotFoundError:
                parts.append('<span style="color: green;">' +
                             _("animation-speech installed") + '</span>')
            self.btn_install_anim.setVisible(False)
        else:
            self.btn_install_anim.setVisible(True)

        # Vérifier le plasmoid
        has_plasmoid = os.path.isdir(
            os.path.expanduser("~/.local/share/plasma/plasmoids/com.github.rcspam.dictee")
        ) or os.path.isdir("/usr/share/plasma/plasmoids/com.github.rcspam.dictee")
        if has_plasmoid:
            parts.append('<span style="color: green;">' +
                         _("Dictee plasmoid installed") + '</span>')

        if parts:
            self.lbl_anim_status.setText(" — ".join(parts))

    def _on_install_animation(self):
        self.btn_install_anim.setEnabled(False)
        self.btn_install_anim.setText(_("Downloading…"))
        self.progress_anim.setVisible(True)

        self._install_thread = InstallThread()
        self._install_thread.progress.connect(lambda text: self.btn_install_anim.setText(text))
        self._install_thread.finished.connect(self._on_install_finished)
        self._install_thread.start()

    def _on_install_finished(self, success, message):
        self.progress_anim.setVisible(False)
        if success:
            self._check_animation_speech()
        else:
            self.btn_install_anim.setText(_("Install animation-speech"))
            self.btn_install_anim.setEnabled(True)
            QMessageBox.critical(self, _("Installation error"), message)

    # -- Appliquer --

    def _on_apply(self):
        if self.radio_ollama.isChecked():
            backend = "ollama"
        elif self.radio_libretranslate.isChecked():
            backend = "libretranslate"
        else:
            backend = "trans"
        lang_src = self.combo_src.currentData()
        lang_tgt = self.combo_tgt.currentData()
        clipboard = self.chk_clipboard.isChecked()

        # Déterminer le mode animation
        a_speech = self.chk_anim_speech.isChecked()
        a_plasmoid = self.chk_plasmoid.isChecked()
        if a_speech and a_plasmoid:
            animation = "both"
        elif a_speech:
            animation = "speech"
        elif a_plasmoid:
            animation = "plasmoid"
        else:
            animation = "none"

        ollama_model = self.combo_ollama_model.currentData()
        ollama_cpu = self.chk_ollama_cpu.isChecked()
        trans_engine = self.combo_trans_engine.currentData()
        lt_port = int(self.spin_lt_port.currentText()) if self.spin_lt_port.currentText().isdigit() else 5000
        # Backend ASR
        if self.rb_vosk.isChecked():
            asr_backend = "vosk"
        elif self.rb_whisper.isChecked():
            asr_backend = "whisper"
        else:
            asr_backend = "parakeet"
        whisper_model = self.cmb_whisper_model.currentText()
        whisper_lang = self.txt_whisper_lang.currentText().strip()
        vosk_model = self.cmb_vosk_lang.currentData() or "fr"

        save_config(backend, lang_src, lang_tgt, clipboard, animation,
                    ollama_model, ollama_cpu, trans_engine, lt_port,
                    asr_backend, whisper_model, whisper_lang, vosk_model)

        # Services systemd — activer le bon daemon ASR, désactiver les autres
        asr_services = {"parakeet": "dictee", "vosk": "dictee-vosk", "whisper": "dictee-whisper"}
        active_svc = asr_services.get(asr_backend, "dictee")
        for svc_name in asr_services.values():
            action = "enable" if svc_name == active_svc else "disable"
            subprocess.run(["systemctl", "--user", action, svc_name], capture_output=True)
        # Si le daemon actif a changé, redémarrer
        if self.chk_daemon.isChecked():
            for svc_name in asr_services.values():
                if svc_name != active_svc:
                    subprocess.run(["systemctl", "--user", "stop", svc_name], capture_output=True)
            subprocess.run(["systemctl", "--user", "restart", active_svc], capture_output=True)

        # Tray
        action = "enable" if self.chk_tray.isChecked() else "disable"
        subprocess.run(["systemctl", "--user", action, "--now", "dictee-tray"], capture_output=True)

        shortcut_msg = ""
        if self.de_type in ("kde", "gnome") and hasattr(self, "btn_capture"):
            shortcuts = [
                (self.btn_capture, self._dictee_existing_desktop or DICTEE_DESKTOP,
                 DICTEE_COMMAND, _("Voice dictation")),
                (self.btn_capture_translate, self._translate_existing_desktop or DICTEE_TRANSLATE_DESKTOP,
                 DICTEE_TRANSLATE_COMMAND, _("Dictation + Translation")),
            ]
            for btn, desktop, cmd, label in shortcuts:
                if not btn._changed:
                    continue
                captured = btn.sequence()
                try:
                    if self.de_type == "kde":
                        accel = qt_key_to_kde(captured)
                        apply_kde_shortcut(accel, desktop, cmd, label, key_sequence=captured)
                        shortcut_msg += "\n" + _("Shortcut applied: {key}").format(key=accel)
                    else:
                        accel = qt_key_to_gnome(captured)
                        apply_gnome_shortcut(accel)
                        shortcut_msg += "\n" + _("Shortcut applied: {key}").format(key=accel)
                except Exception as e:
                    shortcut_msg += "\n" + _("Shortcut error: {err}").format(err=e)

        QMessageBox.information(
            self,
            _("Configuration saved"),
            _("File: {path}").format(path=CONF_PATH) + shortcut_msg,
        )

    def _on_ok(self):
        self._on_apply()
        self.accept()


def main():
    app = QApplication([])
    app.setApplicationName("dictee-setup")
    dialog = DicteeSetupDialog()
    dialog.exec()


if __name__ == "__main__":
    main()
